name = "jezweb-analysis-tool"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "dist"

# KV Namespaces for caching
[[kv_namespaces]]
binding = "CACHE"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID"

# Environment variables
[vars]
APP_NAME = "Jezweb Analysis Tool"
ENVIRONMENT = "production"

# Build configuration
[build]
command = "npm run build"

# Development configuration
[dev]
port = 8788
